# Date created and Last ran : 08-07-2023 
# Queries to solve the Souvenir Case study 
# Source: Cosmo AI Google meeting SQL session by Szimonetta Farkas on 08-06-2023

use demo_database;
-- CREATE TABLE
CREATE TABLE souvenir (
    CUST_NAME VARCHAR(30),
    prod_NAME VARCHAR(50),
    QUANTITY INT(3),
    PRICE DECIMAL(5 , 2 ),
    ORDER_DATE DATE,
    CITY VARCHAR(30),
    CONTINENT VARCHAR(30)
);
-- LOAD TABLE
INSERT INTO souvenir VALUES('Alex','Keychain',5,25,'2023-01-02','Amsterdam','Europe');
INSERT INTO souvenir VALUES('Alex','T-shirt',2,20,'2023-01-02','Amsterdam','Europe');
INSERT INTO souvenir VALUES('Bella','Keychain',3,15,'2023-01-05','Berlin','Europe');
INSERT INTO souvenir VALUES('Bella','Pen',5,15,'2023-01-05','Berlin','Europe');
INSERT INTO souvenir VALUES('Bella','Magnet',10,40,'2023-01-05','Berlin','Europe');
INSERT INTO souvenir VALUES('Daniel','Keychain',10,50,'2023-01-14','NewYork','America');
INSERT INTO souvenir VALUES('Elena','Postcard1',6,12,'2023-01-20','Stockholm','Europe');
INSERT INTO souvenir VALUES('Elena','Postcard2',6,12,'2023-01-20','Stockholm','Europe');
INSERT INTO souvenir VALUES('Fadi','T-shirt',1,10,'2023-01-31','Delhi','India');
INSERT INTO souvenir VALUES('Fadi','Postcard2',15,30,'2023-01-31','Delhi','India');
INSERT INTO souvenir VALUES('Alex','Keychain',10,50,'2023-02-05','Amsterdam','Europe');

-- VALIDATE table looks good 
SELECT * FROM souvenir;

/*Problem statement : Raj, a young businessman decided to open his first Souvenir shops all over the world . He has been collecting his money since 
his childhood to make his dream come true .He wants to understand his customers and his behaviour more . 
He came to you to help him to get useful insights about his business.*/

-- Q1.How many customers we have ?
SELECT  COUNT( DISTINCT cust_name)
FROM souvenir; -- 5 customers 

-- Q2. How many customers we have in Europe?
SELECT COUNT( DISTINCT cust_name)
FROM souvenir
WHERE continent ='Europe'; -- 3 customers 

-- Q3. How many customers we have who are not located in New York?
SELECT COUNT(DISTINCT cust_name)
FROM souvenir
WHERE city <> 'NewYork'; 
-- The answer is 4 customers 

-- 4. How many different types of products we sell ?
SELECT COUNT(DISTINCT prod_name)
FROM souvenir; 
-- Answer : Six  different products 

-- 5. In how many different cities we have customers ?
SELECT COUNT(DISTINCT city)
FROM souvenir; 
-- Answer : we have customers hailing from five different cities 

-- 6. How many continents are available for us ?
SELECT COUNT(DISTINCT continent)
FROM souvenir;
-- Answer: Customers come from three different continents 

-- 7. How much total sales were generated
SELECT SUM(quantity*price) AS TOTAL_SALES
FROM souvenir;
-- We had a total of 2289.00 in sales

-- 8.How much sales were generated in Europe?
SELECT SUM(quantity*price) AS TOTAL_SALES
FROM souvenir
WHERE continent= 'Europe';
-- We had a total of 1329.00 in sales in Europe

-- 9.How much was the average sales in India?
SELECT AVG(quantity*price) AS tot_sales_india
FROM souvenir
WHERE continent= 'India';
-- We had an average sales of $230.00 in India

-- 10.How much sales were generated before 01/02/2023?
SELECT SUM(quantity*price) AS TOTAL_SALES
FROM souvenir
WHERE order_date < '2023-01-02';
-- null returned which means there were no sales before 2nd of January 2023 

-- 11. Create a list of customer names in alphabetical order
SELECT DISTINCT(cust_name)
FROM souvenir
ORDER BY cust_name ASC;
/* Here is the result set for this query
cust_name
Alex
Bella
Daniel
Elena
Fadi
*/

-- 12. How many products were bought by each customer
SELECT 
    cust_name,
    COUNT(prod_name)
FROM
    souvenir
GROUP BY cust_name;
/*
CUST_NAME, COUNT(PROD_NAME)
Alex	3
Bella	3
Daniel	1
Elena	2
Fadi	2
*/

-- 13. How much sales was generated by each customer
SELECT 
    cust_name,
    SUM(quantity*price) AS sales_per_customer
FROM
    souvenir
GROUP BY cust_name;

/* Result set of this query
cust_name, sales_per_customer
Alex	665.00
Bella	520.00
Daniel	500.00
Elena	144.00
Fadi	460.00
*/
-- 14. Name a customer who bought the most number of products
SELECT 
    cust_name,
    SUM(quantity) as num_of_products
FROM
    souvenir
GROUP BY CUST_NAME
ORDER BY num_of_products DESC
LIMIT 1;

/* Answer : Bella has bought a total of 18 units of various souvenir product types from our souvenir shop */

-- 15. Name a customer who bought the least amount of products
SELECT 
    cust_name,
    SUM(quantity) as num_of_products
FROM
    souvenir
GROUP BY CUST_NAME
ORDER BY num_of_products ASC
LIMIT 1;

/* Customer Daniel bought a total of 10 units, which is the least quantity among all customers who bought from our shop */

-- 16.Average sales by each city
SELECT city,
    AVG(quantity*price) AS avg_sales_city
FROM
    souvenir
GROUP BY city;

/* Here is the result set for this query
# city, avg_sales_city
Amsterdam, 221.666667
Berlin, 173.333333
NewYork, 500.000000
Stockholm, 72.000000
Delhi, 230.000000

*/

-- 17.Total sales by each continent .
SELECT continent,
    SUM(quantity * price) AS total_sales_continent
FROM
    souvenir
GROUP BY continent;

/* Here is the result set for this query
# continent, total_sales_continent
Europe, 1329.00
America, 500.00
India, 460.00
*/


